config/routes.rb
Spree::Core::Engine.add_routes do
  resources :comments, only: [:create]
end

app/models/spree/comment.rb
module Spree
  class Comment < Spree::Base
    # https://github.com/jackdempsey/acts_as_commentable/blob/master/lib/comment_methods.rb
    include ActsAsCommentable::Comment

    belongs_to :user, class_name: 'Spree::User'
    belongs_to :product, class_name: 'Spree::Product'
    belongs_to :commentable, polymorphic: true

    has_one :answer, as: :commentable, class_name: 'Spree::Comment'

    validates :user, :body, presence: true
    validates :body, length: { in: 1..140 }
    validates :product, presence: true, unless: 'commentable.present?'

    default_scope { order(created_at: :desc) }

    def is_question?
      commentable.blank?
    end

    def is_answer?
      !is_question?
    end

    def answered?
      is_question? && answer.present?
    end
  end
end

app/models/spree/product_decorator.rb
module Spree
  Product.class_eval do
    has_many :comments, class_name: 'Spree::Comment'
  end
end

app/controllers/spree/comments_controller.rb
module Spree
  class CommentsController < Spree::StoreController
    def create
      # Spree::StoreController already has authenticaiton methods
      # like you can see here
      # https://github.com/spree/spree/blob/v2.3.1/core/lib/spree/core/controller_helpers/auth.rb#L12
      @comment      = Spree::Comment.new(permitted_params)
      @comment.user = try_spree_current_user
      # Set the message depending on the state of the .save method
      @comment.save ? (flash.success = t('spree.comment.success')) : (flash.error = t('spree.comment.failure'))
      redirect_to product_path(@comment.product.slug || @comment.commentable.product.slug)
    end

    protected

    # Spree::StoreController doesn't have a default permitted_params
    # method to define attributes based on some policy...
    # In this case you need to define it manually
    def permitted_params
      params.require(:comment).permit([:body, :commentable_id, :commentable_type,
                                       :product_id])
    end
  end
end

app/views/comments/_form.html.erb
<%= form_for(comment, url: comments_path) do |f| %>
  <%= f.hidden_field :product_id %>
  <%= f.hidden_field :commentable_id %>
  <%= f.hidden_field :commentable_type %>
  <article class="message-box message-box-answer js-answer-box">
    <%= f.text_area :body, class: 'js-answer-input message-box-input' %>
    <span class="message-box-submit">
      <%= button Spree.t(:ask), '' %>
    </span>
  </article>
<% end %>

app/views/comments/_list.html.erb
<div class="message-box-wrapper clearfix">
  <div class="message-box-item">
    <article class="message-box">
      <%= image_tag comment.user.profile_image_url(:thumb), size: '40x40', class: 'message-box-image' %>
      <span class="message-box-info"><%= "#{comment.user.first_name} - perguntou há #{time_ago_in_words(comment.created_at)} - #{product.name}" %></span>
      <p class="message-box-content"><%= comment.body %></p>
    </article>
  </div>

  <% if comment.answer.present? %>
    <div class="message-box-item">
      <article class="message-box">
        <span class="message-box-info"><%= Spree.t(:answer) %></span>
        <p class="message-box-content"><%= comment.answer.body %></p>
      </article>
    </div>

  <% elsif @product.seller_id == try_spree_current_user.try(:id) %>
    <div class="message-box-item">
      <%= render partial: 'comments/form', locals: { comment: comment.build_answer } %>
    </div>
  <% end %>
</div>